# Generated by Django 4.2.4 on 2023-09-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('basics', models.IntegerField(default=0, verbose_name='basics')),
                ('printf_scanf', models.IntegerField(default=0, verbose_name='printf_scanf')),
                ('variables', models.IntegerField(default=0, verbose_name='variables')),
                ('datatypes', models.IntegerField(default=0, verbose_name='datatypes')),
                ('typeConversion', models.IntegerField(default=0, verbose_name='typeConversion')),
                ('conditional_statements', models.IntegerField(default=0, verbose_name='conditional_statements')),
                ('loops', models.IntegerField(default=0, verbose_name='loops')),
                ('break_continue', models.IntegerField(default=0, verbose_name='break_continue')),
                ('strings', models.IntegerField(default=0, verbose_name='strings')),
                ('arrays', models.IntegerField(default=0, verbose_name='arrays')),
                ('pointers', models.IntegerField(default=0, verbose_name='pointers')),
                ('functions', models.IntegerField(default=0, verbose_name='functions')),
                ('files', models.IntegerField(default=0, verbose_name='files')),
                ('structures', models.IntegerField(default=0, verbose_name='structures')),
            ],
        ),
    ]
