# Generated by Django 4.2.4 on 2023-09-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jaav_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('basics', models.PositiveIntegerField(default=0, verbose_name='basics')),
                ('print_scanner', models.PositiveIntegerField(default=0, verbose_name='print_scanner')),
                ('variables', models.PositiveIntegerField(default=0, verbose_name='variables')),
                ('datatypes', models.PositiveIntegerField(default=0, verbose_name='datatypes')),
                ('typeConversion', models.PositiveIntegerField(default=0, verbose_name='typeConversion')),
                ('conditional_statements', models.PositiveIntegerField(default=0, verbose_name='conditional_statements')),
                ('loops', models.PositiveIntegerField(default=0, verbose_name='loops')),
                ('break_continue', models.PositiveIntegerField(default=0, verbose_name='break_continue')),
                ('lists', models.PositiveIntegerField(default=0, verbose_name='lists')),
                ('dictionary', models.PositiveIntegerField(default=0, verbose_name='dictionary')),
                ('pointers', models.PositiveIntegerField(default=0, verbose_name='pointers')),
                ('files', models.PositiveIntegerField(default=0, verbose_name='files')),
                ('classes_objects', models.PositiveIntegerField(default=0, verbose_name='classes_objects')),
                ('ModulesAndPackages', models.PositiveIntegerField(default=0, verbose_name='Modules and Packages')),
            ],
        ),
        migrations.CreateModel(
            name='python_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('basics', models.PositiveIntegerField(default=0, verbose_name='basics')),
                ('print_input', models.PositiveIntegerField(default=0, verbose_name='print_input')),
                ('variables', models.PositiveIntegerField(default=0, verbose_name='variables')),
                ('datatypes', models.PositiveIntegerField(default=0, verbose_name='datatypes')),
                ('typeConversion', models.PositiveIntegerField(default=0, verbose_name='typeConversion')),
                ('conditional_statements', models.PositiveIntegerField(default=0, verbose_name='conditional_statements')),
                ('loops', models.PositiveIntegerField(default=0, verbose_name='loops')),
                ('break_continue', models.PositiveIntegerField(default=0, verbose_name='break_continue')),
                ('lists', models.PositiveIntegerField(default=0, verbose_name='lists')),
                ('dictionary', models.PositiveIntegerField(default=0, verbose_name='dictionary')),
                ('pointers', models.PositiveIntegerField(default=0, verbose_name='pointers')),
                ('files', models.PositiveIntegerField(default=0, verbose_name='files')),
                ('classes_objects', models.PositiveIntegerField(default=0, verbose_name='classes_objects')),
                ('ModulesAndPackages', models.PositiveIntegerField(default=0, verbose_name='Modules and Packages')),
            ],
        ),
        migrations.AlterField(
            model_name='c_language',
            name='arrays',
            field=models.PositiveIntegerField(default=0, verbose_name='arrays'),
        ),
        migrations.AlterField(
            model_name='c_language',
            name='basics',
            field=models.PositiveIntegerField(default=0, verbose_name='basics'),
        ),
        migrations.AlterField(
            model_name='c_language',
            name='break_continue',
            field=models.PositiveIntegerField(default=0, verbose_name='break_continue'),
        ),
        migrations.AlterField(
            model_name='c_language',
            name='conditional_statements',
            field=models.PositiveIntegerField(default=0, verbose_name='conditional_statements'),
        ),
        migrations.AlterField(
            model_name='c_language',
            name='datatypes',
            field=models.PositiveIntegerField(default=0, verbose_name='datatypes'),
        ),
        migrations.AlterField(
            model_name='c_language',
            name='files',
            field=models.PositiveIntegerField(default=0, verbose_name='files'),
        ),
        migrations.AlterField(
            model_name='c_language',
            name='functions',
            field=models.PositiveIntegerField(default=0, verbose_name='functions'),
        ),
        migrations.AlterField(
            model_name='c_language',
            name='loops',
            field=models.PositiveIntegerField(default=0, verbose_name='loops'),
        ),
        migrations.AlterField(
            model_name='c_language',
            name='pointers',
            field=models.PositiveIntegerField(default=0, verbose_name='pointers'),
        ),
        migrations.AlterField(
            model_name='c_language',
            name='printf_scanf',
            field=models.PositiveIntegerField(default=0, verbose_name='printf_scanf'),
        ),
        migrations.AlterField(
            model_name='c_language',
            name='strings',
            field=models.PositiveIntegerField(default=0, verbose_name='strings'),
        ),
        migrations.AlterField(
            model_name='c_language',
            name='structures',
            field=models.PositiveIntegerField(default=0, verbose_name='structures'),
        ),
        migrations.AlterField(
            model_name='c_language',
            name='typeConversion',
            field=models.PositiveIntegerField(default=0, verbose_name='typeConversion'),
        ),
        migrations.AlterField(
            model_name='c_language',
            name='variables',
            field=models.PositiveIntegerField(default=0, verbose_name='variables'),
        ),
    ]
