# Generated by Django 4.2.4 on 2023-09-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jaav_language_python_language_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jaav_language',
            new_name='java_language',
        ),
        migrations.AddField(
            model_name='c_language',
            name='operators',
            field=models.PositiveIntegerField(default=0, max_length=10, verbose_name='operators'),
        ),
    ]
